services:
  dev:
    # extends:
    #   file: ../compose.yml
    #   service: backend
    build: .
    volumes:
      # Mount the parent directory (project root) to /workspace
      - ..:/workspace:cached
      
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    extends:
      file: ../compose.yml
      service: db

volumes:
  db: